### ISSUE TITLE
Anchor links for kroxylicious.io

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious.github.io#31]
It'd be nice if content headings on the kroxylicious.io had copy/pastable anchor links to that users could easily refer to content from other places.

<img width="1412" alt="image" src="https://github.com/kroxylicious/kroxylicious.github.io/assets/18440250/9104c862-b4a3-4f0f-9ac5-e7e57f443802">

**Comment by gracegrimwood** [comment]
[The jekyll-toc plugin](https://github.com/toshimaru/jekyll-toc?tab=readme-ov-file#inject_anchors-filter) has a Liquid filter that does exactly this. We can use `inject_anchors` on content where relevant to inject anchor links on headings.

Note that this won't apply to the docs because that content is compiled and rendered in a different repository, and doesn't use Jekyll.
